const $=id=>document.getElementById(id);
const fileInput=$('fileInput'),dropZone=$('dropZone'),chooseBtn=$('chooseBtn'),filePanel=$('filePanel'),controls=$('controls'),cropBtn=$('cropBtn'),removeBtn=$('removeBtn'),resetBtn=$('resetBtn'),status=$('status'),error=$('error'),result=$('result'),downloadBtn=$('downloadBtn');
let file=null,sourceBytes=null,downloadUrl=null;
function clearMessages(){status.hidden=true;error.hidden=true;result.hidden=true;error.textContent='';if(downloadUrl){URL.revokeObjectURL(downloadUrl);downloadUrl=null}downloadBtn.removeAttribute('href')}
function showError(message){clearMessages();error.textContent=message;error.hidden=false}
function setBusy(on,text='Applying the new page boxes'){status.hidden=!on;if(on){$('statusTitle').textContent='Cropping your PDF…';$('statusText').textContent=text}}
function validPdf(bytes){return bytes&&bytes.length>5&&new TextDecoder().decode(bytes.slice(0,5))==='%PDF-'}
function readFile(f){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(new Uint8Array(r.result));r.onerror=()=>reject(new Error('The PDF could not be read from your device.'));r.readAsArrayBuffer(f)})}
async function loadFile(f){clearMessages();if(!f)return;if(f.type&&f.type!=='application/pdf'&&!/\.pdf$/i.test(f.name)){showError('Please choose a PDF file.');return}try{const bytes=await readFile(f);if(!validPdf(bytes)){showError('This file does not appear to be a valid PDF.');return}file=f;sourceBytes=bytes; $('fileName').textContent=f.name;$('fileMeta').textContent=`${(f.size/1024/1024).toFixed(2)} MB · PDF ready`;filePanel.hidden=false;controls.hidden=false;dropZone.hidden=true}catch(e){showError(e.message||'Could not read this PDF.')}}
function reset(){file=null;sourceBytes=null;fileInput.value='';filePanel.hidden=true;controls.hidden=true;dropZone.hidden=false;clearMessages();$('preset').value='custom';$('top').value=20;$('right').value=20;$('bottom').value=20;$('left').value=20}
chooseBtn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();fileInput.click()});dropZone.addEventListener('click',e=>{if(e.target!==chooseBtn)fileInput.click()});fileInput.addEventListener('change',async e=>{const f=e.target.files?.[0];await loadFile(f);fileInput.value=''});
['dragenter','dragover'].forEach(x=>dropZone.addEventListener(x,e=>{e.preventDefault();dropZone.classList.add('over')}));['dragleave','drop'].forEach(x=>dropZone.addEventListener(x,e=>{e.preventDefault();dropZone.classList.remove('over')}));dropZone.addEventListener('drop',async e=>{await loadFile(e.dataTransfer.files?.[0])});dropZone.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fileInput.click()}});removeBtn.addEventListener('click',reset);resetBtn.addEventListener('click',reset);
const presetValues={small:[10,10,10,10],medium:[24,24,24,24],large:[48,48,48,48]};
$('preset').addEventListener('change',e=>{const v=e.target.value;if(presetValues[v])[$('top').value,$('right').value,$('bottom').value,$('left').value]=presetValues[v];else if(v==='custom'){}else if(v==='fit'){[$('top').value,$('right').value,$('bottom').value,$('left').value]=[0,0,0,0]}});
async function crop(){if(!file||!sourceBytes){showError('Choose a PDF before cropping.');return}clearMessages();const m=['top','right','bottom','left'].map(id=>Math.max(0,Number($(id).value)||0));setBusy(true,'Reading the PDF and applying your crop');cropBtn.disabled=true;try{const doc=await PDFLib.PDFDocument.load(sourceBytes.slice());const pages=doc.getPages();if(!pages.length)throw new Error('The PDF contains no pages.');for(const page of pages){const box=page.getCropBox();const x=m[3],y=m[2],w=box.width-m[1]-m[3],h=box.height-m[0]-m[2];if(w<=10||h<=10)throw new Error('The crop margins are too large for one or more pages. Reduce the margins and try again.');page.setCropBox(box.x+x,box.y+y,w,h)}const out=await doc.save({useObjectStreams:false});if(!out?.length)throw new Error('The cropped PDF could not be created.');downloadUrl=URL.createObjectURL(new Blob([out],{type:'application/pdf'}));downloadBtn.href=downloadUrl;downloadBtn.download='nexauren-cropped.pdf';setBusy(false);$('resultMeta').textContent=`${pages.length} page${pages.length===1?'':'s'} · ${(out.length/1024/1024).toFixed(2)} MB`;result.hidden=false}catch(e){setBusy(false);showError(e?.message||'We couldn’t crop this PDF. Try another file.')}finally{cropBtn.disabled=false}}
cropBtn.addEventListener('click',crop);clearMessages();