const $=id=>document.getElementById(id);const drop=$('drop'),input=$('file'),choose=$('choose'),workspace=$('workspace'),fileName=$('fileName'),fileMeta=$('fileMeta'),password=$('password'),confirmPassword=$('confirm'),protect=$('protect'),remove=$('remove'),status=$('status'),statusTitle=$('statusTitle'),statusText=$('statusText'),error=$('error'),result=$('result'),resultText=$('resultText'),download=$('download'),again=$('again');let file=null,objectUrl=null;
function clearMessages(){status.hidden=true;error.hidden=true;result.hidden=true;error.textContent='';if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null}download.removeAttribute('href')}
function showError(msg){status.hidden=true;result.hidden=true;error.textContent=msg;error.hidden=false}
function formatBytes(n){if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(2)+' MB'}
function validPdf(f){return !!f&&(/\.pdf$/i.test(f.name)||f.type==='application/pdf')}
function setFile(f){clearMessages();if(!validPdf(f))return showError('Please choose a valid PDF file.');file=f;fileName.textContent=f.name;fileMeta.textContent=`${formatBytes(f.size)} · PDF ready`;workspace.hidden=false;drop.hidden=true;password.value='';confirmPassword.value=''}
choose.addEventListener('click',e=>{e.stopPropagation();input.click()});drop.addEventListener('click',()=>input.click());drop.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}});input.addEventListener('change',()=>{const f=input.files?.[0];input.value='';if(f)setFile(f)});
['dragenter','dragover'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>{const f=e.dataTransfer.files?.[0];if(f)setFile(f)});
remove.addEventListener('click',()=>reset());again.addEventListener('click',()=>reset());
async function protectPdf(){clearMessages();if(!file)return showError('Choose a PDF first.');const p=password.value.trim(),c=confirmPassword.value.trim();if(p.length<4)return showError('Use a password with at least 4 characters.');if(p!==c)return showError('The passwords do not match.');protect.disabled=true;status.hidden=false;statusTitle.textContent='Protecting your PDF…';statusText.textContent='Encrypting locally in your browser';try{const bytes=new Uint8Array(await file.arrayBuffer());if(!(bytes[0]===37&&bytes[1]===80&&bytes[2]===68&&bytes[3]===70&&bytes[4]===45))throw new Error('The selected file does not contain a valid PDF header.');const encrypted=await PDFEncryptLite.encryptPDF(bytes,p);if(!encrypted||encrypted.length<100)throw new Error('The encryption library returned an invalid PDF.');const blob=new Blob([encrypted],{type:'application/pdf'});objectUrl=URL.createObjectURL(blob);download.href=objectUrl;download.download=file.name.replace(/\.pdf$/i,'')+'-protected.pdf';resultText.textContent=`Protected copy created · ${formatBytes(encrypted.length)}`;status.hidden=true;workspace.hidden=true;result.hidden=false}catch(err){console.error(err);showError(err?.message||'We could not protect this PDF. Try another PDF.')}finally{protect.disabled=false}}
protect.addEventListener('click',protectPdf);
function reset(){if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null}file=null;workspace.hidden=true;drop.hidden=false;password.value='';confirmPassword.value='';clearMessages()}
clearMessages();
