const $=id=>document.getElementById(id);
const dropzone=$('dropzone'),input=$('fileInput'),workspace=$('workspace'),thumbs=$('thumbs'),status=$('status'),result=$('result'),errorBox=$('error');
let images=[],pdfUrl=null,dragIndex=-1;
function show(e){e.classList.remove('hidden')}function hide(e){e.classList.add('hidden')}
function fmt(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(2)+' MB'}
function baseName(n){return n.replace(/\.[^.]+$/,'').replace(/[^a-z0-9-_]+/gi,'-').replace(/^-|-$/g,'')||'images'}
function err(t){errorBox.textContent=t;show(errorBox)}
function render(){thumbs.innerHTML='';$('fileCount').textContent=images.length+' image'+(images.length===1?'':'s');images.forEach((item,i)=>{const card=document.createElement('article');card.className='thumb';card.draggable=true;card.dataset.index=i;const img=document.createElement('img');img.src=item.url;img.alt=item.file.name;const meta=document.createElement('div');meta.className='thumb-meta';const num=document.createElement('span');num.className='number';num.textContent=i+1;const name=document.createElement('span');name.className='thumb-name';name.textContent=item.file.name;meta.append(num,name);const size=document.createElement('span');size.className='thumb-size';size.textContent=fmt(item.file.size);const remove=document.createElement('button');remove.className='thumb-remove';remove.type='button';remove.textContent='×';remove.setAttribute('aria-label','Remove '+item.file.name);remove.onclick=e=>{e.stopPropagation();removeAt(i)};card.append(img,meta,size,remove);thumbs.appendChild(card);card.addEventListener('dragstart',()=>{dragIndex=i;card.classList.add('dragging')});card.addEventListener('dragend',()=>{dragIndex=-1;card.classList.remove('dragging')});card.addEventListener('dragover',e=>e.preventDefault());card.addEventListener('drop',e=>{e.preventDefault();if(dragIndex<0||dragIndex===i)return;const moved=images.splice(dragIndex,1)[0];images.splice(i,0,moved);render()})});if(images.length){show(workspace);hide(dropzone)}else reset()}
function addFiles(list){hide(errorBox);const files=[...list].filter(f=>f.type==='image/jpeg'||/\.jpe?g$/i.test(f.name));if(!files.length){err('Please choose one or more valid JPG images.');return}files.forEach(file=>images.push({file,url:URL.createObjectURL(file)}));render()}
function removeAt(i){const item=images.splice(i,1)[0];if(item)URL.revokeObjectURL(item.url);render()}
function reset(){images.forEach(x=>URL.revokeObjectURL(x.url));images=[];input.value='';if(pdfUrl){URL.revokeObjectURL(pdfUrl);pdfUrl=null}hide(workspace);hide(status);hide(result);hide(errorBox);show(dropzone);thumbs.innerHTML=''}
function pageSizeFor(w,h,orientation,margin){if($('pageSize').value==='fit')return{w:w+margin*2,h:h+margin*2};let size=$('pageSize').value==='a4'?{w:595.28,h:841.89}:{w:612,h:792};if(orientation==='landscape'||(orientation==='auto'&&w>h))[size.w,size.h]=[size.h,size.w];return size}
async function imageDimensions(file){return await new Promise((resolve,reject)=>{const img=new Image();const url=URL.createObjectURL(file);img.onload=()=>{resolve({w:img.naturalWidth,h:img.naturalHeight});URL.revokeObjectURL(url)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('An image could not be read.'))};img.src=url})}
async function convert(){if(!images.length)return;hide(errorBox);hide(result);show(status);$('convertBtn').disabled=true;try{const{PDFDocument}=PDFLib;const doc=await PDFDocument.create();const margin=Number($('margin').value),orientation=$('orientation').value;for(let i=0;i<images.length;i++){ $('statusTitle').textContent='Creating PDF…';$('statusText').textContent='Adding image '+(i+1)+' of '+images.length;const item=images[i],bytes=await item.file.arrayBuffer(),jpg=await doc.embedJpg(bytes),dim=await imageDimensions(item.file),ps=pageSizeFor(dim.w,dim.h,orientation,margin),page=doc.addPage([ps.w,ps.h]),availW=ps.w-margin*2,availH=ps.h-margin*2,scale=Math.min(availW/dim.w,availH/dim.h),drawW=dim.w*scale,drawH=dim.h*scale;page.drawImage(jpg,{x:(ps.w-drawW)/2,y:(ps.h-drawH)/2,width:drawW,height:drawH});await new Promise(r=>setTimeout(r,0))}$('statusTitle').textContent='Finishing…';$('statusText').textContent='Preparing your download';const bytes=await doc.save(),blob=new Blob([bytes],{type:'application/pdf'});pdfUrl=URL.createObjectURL(blob);$('downloadBtn').href=pdfUrl;$('downloadBtn').download=(images.length===1?baseName(images[0].file.name):baseName(images[0].file.name)+'-images')+'.pdf';$('resultText').textContent=images.length+' image'+(images.length===1?'':'s')+' combined into a '+fmt(blob.size)+' PDF.';hide(status);show(result)}catch(e){hide(status);err(e&&e.message?e.message:'The images could not be converted. Please try again.')}finally{$('convertBtn').disabled=false}}
$('chooseBtn').onclick=()=>input.click();input.onchange=e=>addFiles(e.target.files);$('clearBtn').onclick=reset;$('restartBtn').onclick=reset;$('convertBtn').onclick=convert;['dragenter','dragover'].forEach(x=>dropzone.addEventListener(x,e=>{e.preventDefault();dropzone.classList.add('drag')}));['dragleave','drop'].forEach(x=>dropzone.addEventListener(x,e=>{e.preventDefault();dropzone.classList.remove('drag')}));dropzone.addEventListener('drop',e=>addFiles(e.dataTransfer.files));dropzone.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}});
