const $=id=>document.getElementById(id);
const dz=$('dropzone'),input=$('fileInput'),workspace=$('workspace'),status=$('status'),result=$('result'),errorBox=$('error');
let file=null,buffer=null;
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
const show=e=>e.classList.remove('hidden'),hide=e=>e.classList.add('hidden');
function fmt(n){if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(2)+' MB'}
function fail(s){errorBox.textContent=s;show(errorBox)}
function reset(){file=null;buffer=null;input.value='';hide(workspace);hide(status);hide(result);hide(errorBox);show(dz);$('downloads').innerHTML=''}
async function loadFile(f){hide(errorBox);if(!f||f.type!=='application/pdf'){fail('Please choose a valid PDF file.');return}file=f;buffer=await f.arrayBuffer();try{const p=await pdfjsLib.getDocument({data:buffer.slice(0)}).promise;$('fileName').textContent=f.name;$('fileInfo').textContent=`${p.numPages} page${p.numPages===1?'':'s'} · ${fmt(f.size)}`;show(workspace);hide(dz)}catch(e){reset();fail('This PDF could not be opened. Check the file and try again.')}}
function baseName(n){return n.replace(/\.pdf$/i,'').replace(/[^a-z0-9-_]+/gi,'-').replace(/^-|-$/g,'')||'document'}
async function convert(){if(!file)return;hide(errorBox);hide(result);show(status);$('convertBtn').disabled=true;try{const p=await pdfjsLib.getDocument({data:buffer.slice(0)}).promise;const q=+$('quality').value,s=+$('scale').value,base=baseName(file.name),box=$('downloads');box.innerHTML='';for(let i=1;i<=p.numPages;i++){ $('statusTitle').textContent='Converting…';$('statusText').textContent=`Rendering page ${i} of ${p.numPages}`;const page=await p.getPage(i),v=page.getViewport({scale:s}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);const x=c.getContext('2d',{alpha:false});x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);await page.render({canvasContext:x,viewport:v}).promise;const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',q));if(!blob)throw Error('JPG creation failed');const a=document.createElement('a');a.className='download';a.href=URL.createObjectURL(blob);a.download=`${base}-page-${String(i).padStart(2,'0')}.jpg`;a.innerHTML=`<span>JPG · Page ${i}</span><span>${fmt(blob.size)} · Download ↓</span>`;box.appendChild(a);await new Promise(r=>setTimeout(r,0))}hide(status);show(result);$('resultText').textContent=`${p.numPages} JPG image${p.numPages===1?'':'s'} created successfully.`}catch(e){hide(status);fail(e.message||'The PDF could not be converted. Please try another file.')}finally{$('convertBtn').disabled=false}}
$('chooseBtn').onclick=()=>input.click();input.onchange=e=>loadFile(e.target.files[0]);$('removeBtn').onclick=reset;$('restartBtn').onclick=reset;$('convertBtn').onclick=convert;
['dragenter','dragover'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));dz.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}});
