const $=s=>document.querySelector(s);
const input=$("#file"),drop=$("#dropzone"),workspace=$("#workspace"),status=$("#status"),result=$("#result");
let file=null,mode="range",parts=[];
function esc(v){return v.replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
function err(v){status.className="status error";status.textContent=v}
async function loadFile(f){if(!f||(f.type!=="application/pdf"&&!f.name.toLowerCase().endsWith(".pdf"))){err("Please choose a valid PDF file.");return}file=f;status.className="status";status.textContent="Reading PDF…";try{const doc=await PDFLib.PDFDocument.load(await f.arrayBuffer());$("#fileName").textContent=f.name;$("#pageInfo").textContent=`${doc.getPageCount()} pages · ${f.size/1048576<1?(f.size/1024).toFixed(1)+" KB":(f.size/1048576).toFixed(2)+" MB"}`;workspace.classList.remove("hidden");drop.classList.add("hidden");status.textContent="";result.classList.add("hidden")}catch(e){err("We couldn't read this PDF. Make sure the file is valid and try again.")}}
$("#choose").onclick=()=>input.click();drop.onclick=e=>{if(e.target!==$("#choose"))input.click()};input.onchange=()=>{loadFile(input.files[0]);input.value=""};
["dragenter","dragover"].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add("drag")}));["dragleave","drop"].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove("drag")}));drop.addEventListener("drop",e=>loadFile(e.dataTransfer.files[0]));
$("#change").onclick=()=>input.click();
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));$("#rangeMode").classList.toggle("hidden",mode!=="range");$("#eachMode").classList.toggle("hidden",mode!=="each")});
function parseRanges(text,total){const out=[];for(const raw of text.split(",")){const s=raw.trim();if(!s)continue;const m=s.match(/^(\d+)\s*-\s*(\d+)$/);if(m){let a=+m[1],b=+m[2];if(a<1||b<a||b>total)throw Error("range");out.push([a,b])}else if(/^\d+$/.test(s)){const n=+s;if(n<1||n>total)throw Error("page");out.push([n,n])}else throw Error("format")}return out}
async function makePdf(src,a,b){const out=await PDFLib.PDFDocument.create();const pages=await out.copyPages(src,Array.from({length:b-a+1},(_,i)=>a+i-1));pages.forEach(p=>out.addPage(p));return new Blob([await out.save()],{type:"application/pdf"})}
$("#split").onclick=async()=>{if(!file)return;const btn=$("#split");btn.disabled=true;btn.textContent="Splitting…";status.className="status";try{const src=await PDFLib.PDFDocument.load(await file.arrayBuffer());const total=src.getPageCount();let ranges;if(mode==="each")ranges=Array.from({length:total},(_,i)=>[i+1,i+1]);else{ranges=parseRanges($("#ranges").value,total);if(!ranges.length)throw Error("empty")};parts=[];for(let i=0;i<ranges.length;i++){status.textContent=`Creating part ${i+1} of ${ranges.length}…`;const [a,b]=ranges[i];parts.push({blob:await makePdf(src,a,b),name:`${file.name.replace(/\.pdf$/i,"")}-pages-${a}${b!==a?`-${b}`:""}.pdf`})}result.classList.remove("hidden");$("#resultText").textContent=`Created ${parts.length} separate PDF${parts.length===1?"":"s"}.`;status.textContent="";result.scrollIntoView({behavior:"smooth",block:"center"})}catch(e){err(e.message==="format"?"Use a format such as 1-3, 5, 8-10.":e.message==="range"||e.message==="page"?"One of the selected pages is outside the PDF.":"Please enter the pages you want to split.")}finally{btn.disabled=false;btn.textContent="Split PDF"}};
$("#downloadAll").onclick=async()=>{if(!parts.length)return;const btn=$("#downloadAll");btn.disabled=true;btn.textContent="Preparing ZIP…";try{const zip=new JSZip();parts.forEach(p=>zip.file(p.name,p.blob));const blob=await zip.generateAsync({type:"blob"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="nexauren-split-pdfs.zip";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}finally{btn.disabled=false;btn.textContent="Download ZIP"}};
$("#again").onclick=()=>{file=null;parts=[];workspace.classList.add("hidden");drop.classList.remove("hidden");result.classList.add("hidden");status.textContent="";$("#ranges").value="";window.scrollTo({top:0,behavior:"smooth"})};
