const { PDFDocument } = PDFLib;
const input=document.getElementById('fileInput'),dropZone=document.getElementById('dropZone'),chooseBtn=document.getElementById('chooseBtn'),addBtn=document.getElementById('addBtn'),clearBtn=document.getElementById('clearBtn'),grid=document.getElementById('imageGrid'),workspace=document.getElementById('workspace'),createBtn=document.getElementById('createBtn'),status=document.getElementById('status'),statusTitle=document.getElementById('statusTitle'),statusText=document.getElementById('statusText'),errorBox=document.getElementById('errorBox'),errorText=document.getElementById('errorText'),result=document.getElementById('result'),resultText=document.getElementById('resultText'),downloadBtn=document.getElementById('downloadBtn'),resetBtn=document.getElementById('resetBtn'),sizeSelect=document.getElementById('sizeSelect'),orientationSelect=document.getElementById('orientationSelect'),marginSelect=document.getElementById('marginSelect');
let files=[],outputBlob=null,draggedIndex=null;
function clearMessages(){errorBox.hidden=true;result.hidden=true;status.hidden=true}
function showError(message){status.hidden=true;result.hidden=true;errorText.textContent=message;errorBox.hidden=false}
function setProgress(title,text){statusTitle.textContent=title;statusText.textContent=text;status.hidden=false}
function updateProgress(text){statusText.textContent=text}
function render(){workspace.hidden=!files.length;if(!files.length){grid.innerHTML='';return}grid.innerHTML='';files.forEach((file,index)=>{const card=document.createElement('div');card.className='image-card';card.draggable=true;const thumb=document.createElement('div');thumb.className='thumb';const img=document.createElement('img');img.alt=file.name;img.src=URL.createObjectURL(file);thumb.appendChild(img);const footer=document.createElement('div');footer.className='card-footer';const name=document.createElement('div');name.className='file-name';name.textContent=`${index+1}. ${file.name}`;const remove=document.createElement('button');remove.className='remove';remove.type='button';remove.textContent='×';remove.setAttribute('aria-label',`Remove ${file.name}`);remove.onclick=e=>{e.stopPropagation();files.splice(index,1);render()};footer.append(name,remove);card.append(thumb,footer);card.ondragstart=()=>{draggedIndex=index;card.classList.add('dragging')};card.ondragend=()=>card.classList.remove('dragging');card.ondragover=e=>e.preventDefault();card.ondrop=e=>{e.preventDefault();if(draggedIndex===null||draggedIndex===index)return;const [moved]=files.splice(draggedIndex,1);files.splice(index,0,moved);draggedIndex=null;render()};grid.appendChild(card)})}
function addFiles(list){const accepted=Array.from(list).filter(f=>['image/jpeg','image/png','image/webp'].includes(f.type));if(!accepted.length){showError('Please choose JPG, PNG or WebP images.');return}files.push(...accepted);files=files.filter((f,i,a)=>a.findIndex(x=>x.name===f.name&&x.size===f.size&&x.lastModified===f.lastModified)===i);clearMessages();render()}
function readImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error(`Could not read ${file.name}.`))};img.src=url})}
async function imageForPdf(file){if(file.type==='image/jpeg'||file.type==='image/png'){const bytes=new Uint8Array(await file.arrayBuffer());if(!bytes.length)throw new Error(`Could not read ${file.name}.`);return{bytes,type:file.type}}try{const img=await readImage(file),scale=Math.min(1,2400/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error(`Could not prepare ${file.name}.`);ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error(`Could not prepare ${file.name}.`)),'image/jpeg',.92));return{bytes:new Uint8Array(await blob.arrayBuffer()),type:'image/jpeg'}}catch(e){throw new Error(e?.message||`Could not read ${file.name}.`)} }
function pageDimensions(w,h){const mode=sizeSelect.value;let pw=w,ph=h;if(mode==='a4'){pw=595.28;ph=841.89}else if(mode==='letter'){pw=612;ph=792}if(mode!=='fit'){const landscape=orientationSelect.value==='landscape'||(orientationSelect.value==='auto'&&w>h);if(landscape&&ph>pw)[pw,ph]=[ph,pw];if(orientationSelect.value==='portrait'&&pw>ph)[pw,ph]=[ph,pw]}return[pw,ph]}
async function createPdf(){if(!files.length){showError('Add at least one image before creating the PDF.');return}clearMessages();createBtn.disabled=true;setProgress('Creating your PDF…',`Preparing image 1 of ${files.length}`);try{const pdf=await PDFDocument.create(),margin=Number(marginSelect.value);for(let i=0;i<files.length;i++){updateProgress(`Processing image ${i+1} of ${files.length}`);const source=await imageForPdf(files[i]);const image=source.type==='image/png'?await pdf.embedPng(source.bytes):await pdf.embedJpg(source.bytes);const[pw,ph]=pageDimensions(image.width,image.height),page=pdf.addPage([pw,ph]),maxW=Math.max(1,pw-margin*2),maxH=Math.max(1,ph-margin*2),scale=Math.min(maxW/image.width,maxH/image.height),dw=image.width*scale,dh=image.height*scale;page.drawImage(image,{x:(pw-dw)/2,y:(ph-dh)/2,width:dw,height:dh})}updateProgress('Finalizing your PDF…','Almost done');const bytes=await pdf.save({useObjectStreams:true});if(!bytes?.length)throw new Error('The PDF could not be created.');outputBlob=new Blob([bytes],{type:'application/pdf'});status.hidden=true;resultText.textContent=`${files.length} image${files.length===1?'':'s'} combined · ${(outputBlob.size/1024/1024).toFixed(2)} MB`;result.hidden=false}catch(err){showError(err?.message||'The images could not be converted. Try different files.')}finally{createBtn.disabled=false}}
function download(){if(!outputBlob)return;const url=URL.createObjectURL(outputBlob),a=document.createElement('a');a.href=url;a.download='nexauren-images-to-pdf.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function reset(){files=[];outputBlob=null;draggedIndex=null;input.value='';clearMessages();render();window.scrollTo({top:0,behavior:'smooth'})}
chooseBtn.onclick=e=>{e.stopPropagation();input.click()};addBtn.onclick=e=>{e.stopPropagation();input.click()};dropZone.onclick=e=>{if(e.target.closest('button'))return;input.click()};dropZone.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}};input.onchange=()=>{addFiles(input.files);input.value=''};dropZone.ondragover=e=>{e.preventDefault();dropZone.classList.add('dragover')};dropZone.ondragleave=()=>dropZone.classList.remove('dragover');dropZone.ondrop=e=>{e.preventDefault();dropZone.classList.remove('dragover');addFiles(e.dataTransfer.files)};clearBtn.onclick=reset;createBtn.onclick=createPdf;downloadBtn.onclick=download;resetBtn.onclick=reset;
clearMessages();render();