const registryUrl = "/data/tools.json";
let registryPromise = null;
const extraCategories = [
  {slug:"ai", name:"AI", tools:[]}
];
async function loadRegistry(){if(!registryPromise){registryPromise=fetch(registryUrl,{cache:"no-cache"}).then(response=>{if(!response.ok)throw new Error(`Failed to load ${registryUrl}: ${response.status}`);return response.json()}).then(data=>Array.isArray(data)?data:data.tools).then(list=>Array.isArray(list)?list:[])}return registryPromise}
export async function getTools(){return loadRegistry()}
export async function getCategories(){const tools=await loadRegistry(),categories=new Map();for(const category of extraCategories)categories.set(category.slug,{...category,tools:[]});for(const tool of tools){if(!tool.category)continue;if(!categories.has(tool.category))categories.set(tool.category,{slug:tool.category,name:formatCategoryName(tool.category),tools:[]});if(tool.status==="published")categories.get(tool.category).tools.push(tool)}return [...categories.values()]}
export async function getCategory(categorySlug){const categories=await getCategories();return categories.find(category=>category.slug===categorySlug)||null}
export async function getToolsForCategory(categorySlug){const category=await getCategory(categorySlug);return category?category.tools:[]}
export async function renderCategory(container,categorySlug){if(!container)return;const category=await getCategory(categorySlug);if(!category){container.innerHTML="";return}container.innerHTML=category.tools.map(renderToolCard).join("")}
export async function renderAllCategories(container){if(!container)return;const categories=await getCategories();container.innerHTML=categories.filter(category=>category.tools.length).map(category=>`<section class="tools-category" data-category="${escapeHtml(category.slug)}"><div class="category-header"><div><h2>${escapeHtml(category.name)}</h2><span>${category.tools.length} tool${category.tools.length===1?"":"s"}</span></div></div><div class="tools-grid">${category.tools.map(renderToolCard).join("")}</div></section>`).join("")}
function renderToolCard(tool){return `<article class="tool-card" data-tool-id="${escapeHtml(tool.id)}"><a class="tool-card-main" href="${escapeHtml(tool.toolPath)}"><div class="tool-icon">${escapeHtml(tool.icon||"◈")}</div><div class="tool-info"><div class="tool-title-row"><h3>${escapeHtml(tool.name)}</h3><span class="tool-status">${escapeHtml(tool.status)}</span></div><p>${escapeHtml(tool.description||"")}</p><span class="tool-open">Open tool →</span></div></a><button class="tool-info-button" type="button" aria-label="Information about ${escapeHtml(tool.name)}" data-tool-info="${escapeHtml(tool.id)}">ℹ️</button></article>`}
export async function getToolInfo(toolId){const tools=await loadRegistry();return tools.find(tool=>tool.id===toolId)||null}
function formatCategoryName(slug){if(slug.toLowerCase()==="ai")return "AI";return slug.split("-").map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(" ")}
function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function installMobileToolLibraryStyles(){if(document.getElementById("nexauren-category-mobile-styles"))return;const style=document.createElement("style");style.id="nexauren-category-mobile-styles";style.textContent=`@media(max-width:680px){.tools-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.tool-card{position:relative!important;display:flex!important;flex-direction:column!important;min-width:0!important;min-height:0!important;height:auto!important;padding:14px!important;gap:12px!important}.tool-card-main{display:flex!important;flex-direction:column!important;gap:10px!important;min-width:0!important;width:100%!important}.tool-icon{width:42px!important;height:42px!important;flex:none!important}.tool-info{width:100%!important;min-width:0!important}.tool-title-row{padding-right:26px!important;align-items:flex-start!important}.tool-info h3{font-size:14px!important;line-height:1.25!important;overflow-wrap:anywhere!important}.tool-info p{font-size:12px!important;line-height:1.5!important;display:block!important;overflow:visible!important;white-space:normal!important}.tool-status{font-size:8px!important;padding:4px 6px!important}.tool-open{width:100%!important;justify-content:center!important;font-size:10px!important;padding:9px 7px!important;margin-top:11px!important;white-space:normal!important;text-align:center!important}.tool-info-button{position:absolute!important;top:12px!important;right:12px!important;width:31px!important;height:31px!important;z-index:2}}`;document.head.appendChild(style)}
if(typeof document!=="undefined")installMobileToolLibraryStyles();
