const els={drop:document.querySelector('#drop'),choose:document.querySelector('#choose'),file:document.querySelector('#file'),workspace:document.querySelector('#workspace'),fileName:document.querySelector('#fileName'),fileMeta:document.querySelector('#fileMeta'),password:document.querySelector('#password'),remove:document.querySelector('#remove'),unlock:document.querySelector('#unlock'),status:document.querySelector('#status'),statusText:document.querySelector('#statusText'),error:document.querySelector('#error'),result:document.querySelector('#result'),resultText:document.querySelector('#resultText'),download:document.querySelector('#download'),again:document.querySelector('#again')};
let selectedFile=null,downloadUrl=null;
const QPDF_VERSION='0.2.1';
const QPDF_BASE=`https://cdn.jsdelivr.net/npm/qpdf-run@${QPDF_VERSION}/vendor/qpdf/`;
const clearMessages=()=>{els.status.hidden=true;els.error.hidden=true;els.result.hidden=true;els.error.textContent='';};
const formatBytes=n=>n<1024*1024?`${(n/1024).toFixed(1)} KB`:`${(n/1024/1024).toFixed(2)} MB`;
function reset(){if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=null;selectedFile=null;els.file.value='';els.password.value='';els.fileName.textContent='';els.fileMeta.textContent='';els.workspace.hidden=true;els.drop.hidden=false;clearMessages();}
function showError(message){els.status.hidden=true;els.error.textContent=message;els.error.hidden=false;}
async function readFile(file){const bytes=new Uint8Array(await file.arrayBuffer());if(bytes.length<5||new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')throw new Error('The selected file does not appear to be a valid PDF.');return bytes;}
function loadFile(file){if(!file)return;if(!/\\.pdf$/i.test(file.name)&&file.type!=='application/pdf'){showError('Please choose a PDF file.');return}selectedFile=file;els.fileName.textContent=file.name;els.fileMeta.textContent=formatBytes(file.size);els.drop.hidden=true;els.workspace.hidden=false;clearMessages();els.password.focus();}
async function unlockPdf(){clearMessages();if(!selectedFile){showError('Choose a PDF first.');return}const password=els.password.value;if(!password){showError('Enter the PDF password you are authorized to use.');els.password.focus();return}els.status.hidden=false;els.statusText.textContent='Decrypting locally with QPDF WebAssembly…';els.unlock.disabled=true;try{const bytes=await readFile(selectedFile);const {createQpdfRunner}=await import(`https://cdn.jsdelivr.net/npm/qpdf-run@${QPDF_VERSION}/+esm`);const qpdf=await createQpdfRunner({assetBaseUrl:QPDF_BASE});try{const result=await qpdf.run({inputs:{'input.pdf':bytes.slice()},args:['--password='+password,'--decrypt','--','input.pdf','output.pdf'],outputs:['output.pdf']});if(!result.ok)throw new Error((result.stderr||[]).join(' ')||'QPDF could not unlock this PDF.');const out=result.outputs?.['output.pdf'];if(!out||!out.length)throw new Error('QPDF completed without producing an output PDF.');downloadUrl=URL.createObjectURL(new Blob([out],{type:'application/pdf'}));els.download.href=downloadUrl;els.resultText.textContent=`Unlocked locally · ${formatBytes(out.length)}`;els.status.hidden=true;els.result.hidden=false;}finally{await qpdf.destroy().catch(()=>{});}}catch(error){console.error('PDF Unlock:',error);const text=String(error?.message||error);const wrong=/password|encrypt|decrypt|invalid|incorrect|authentication/i.test(text);showError(wrong?'The password may be incorrect, or this PDF uses an encryption format that QPDF cannot unlock in the browser.':'We could not unlock this PDF. Please verify the file and try again.');}finally{els.unlock.disabled=false;}}
els.choose.addEventListener('click',e=>{e.stopPropagation();els.file.click()});els.drop.addEventListener('click',()=>els.file.click());els.drop.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();els.file.click()}});els.file.addEventListener('change',()=>{const f=els.file.files?.[0];els.file.value='';loadFile(f)});['dragenter','dragover'].forEach(type=>els.drop.addEventListener(type,e=>{e.preventDefault();els.drop.classList.add('drag')}));['dragleave','drop'].forEach(type=>els.drop.addEventListener(type,e=>{e.preventDefault();els.drop.classList.remove('drag')}));els.drop.addEventListener('drop',e=>loadFile(e.dataTransfer.files?.[0]));els.remove.addEventListener('click',reset);els.again.addEventListener('click',reset);els.unlock.addEventListener('click',unlockPdf);els.password.addEventListener('keydown',e=>{if(e.key==='Enter')unlockPdf()});clearMessages();
