const root=document.querySelector("#events"),message=document.querySelector("#message"),count=document.querySelector("#eventCount"),totalViews=document.querySelector("#totalViews"),totalClicks=document.querySelector("#totalClicks"),todayViews=document.querySelector("#todayViews"),planPanel=document.querySelector("#planPanel"),modal=document.querySelector("#editModal"),form=document.querySelector("#editForm"),editMessage=document.querySelector("#editMessage"),editTheme=document.querySelector("#editTheme");
let events=[],editingId=null,stats={},planInfo={plan:"free",maxEvents:3,eventsUsed:0,allowedThemes:["default","conference","birthday","sale"],statistics:false};
const themeNames={default:"Nexauren Classic",conference:"Conference / Summit",wedding:"Wedding / Celebration",birthday:"Birthday / Party",sale:"Sale / Flash Deal",launch:"Product Launch",webinar:"Webinar / Workshop",survey:"Research / Survey",ocean:"Ocean / Beach",sunset:"Sunset / Social",mint:"Mint / Wellness"};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString(undefined,{dateStyle:"medium",timeStyle:"short"})};
const zones=()=>[...new Set(["UTC",Intl.DateTimeFormat().resolvedOptions().timeZone,"Europe/Lisbon","Africa/Maputo","Europe/Paris","America/New_York","America/Los_Angeles","Asia/Dubai","Asia/Tokyo"].filter(Boolean))];
function fillZones(){const s=document.querySelector("#editTimezone");zones().forEach(z=>{const o=document.createElement("option");o.value=z;o.textContent=z;s.appendChild(o)})}
function embedCode(url,name){return`<iframe src="${url}" width="100%" height="300" frameborder="0" loading="lazy" title="${String(name||"Nexauren Event Countdown").replace(/"/g,"&quot;")}"></iframe>`}
function planLabel(){return planInfo.plan.charAt(0).toUpperCase()+planInfo.plan.slice(1)}
function upgradeLink(){return`<a class="upgrade-link" href="/plans/">Upgrade plan →</a>`}
function renderPlan(){
  const p=planInfo.plan,limit=planInfo.maxEvents,used=planInfo.eventsUsed,themes=planInfo.allowedThemes||[];
  const eventText=limit===null?`${used.toLocaleString()} events · Unlimited`:`${used} / ${limit} events used`;
  const stats=planInfo.statistics?`<span class="feature unlocked">✓ Statistics</span>`:`<span class="feature locked">🔒 Statistics · Pro</span>`;
  const themeText=p==="free"?"4 of 11 themes unlocked":"All 11 themes unlocked";
  planPanel.innerHTML=`<div class="plan-main"><div class="plan-kicker">YOUR EVENT COUNTDOWN PLAN</div><div class="plan-title"><strong>${esc(planLabel())}</strong><span class="plan-badge">${esc(p.toUpperCase())}</span></div><div class="plan-features"><span class="feature">◷ ${esc(eventText)}</span><span class="feature">✦ ${esc(themeText)}</span>${stats}</div></div><div class="plan-side">${p==="free"?`${upgradeLink()}<small>Unlock all themes, 20 events and statistics.</small>`:p==="pro"?`${upgradeLink()}<small>Upgrade to Premium for unlimited events.</small>`:`<small>You have access to all Event Countdown features.</small>`}</div>`;
}
function applyThemeLocks(){
  [...editTheme.options].forEach(o=>{
    const allowed=(planInfo.allowedThemes||[]).includes(o.value);
    o.disabled=!allowed;
    o.textContent=allowed?themeNames[o.value]:`🔒 ${themeNames[o.value]} · ${planInfo.plan==="free"?"Pro":"Premium"}`;
  });
}
function render(){
  count.textContent=events.length;let views=0,clicks=0,today=0;const todayKey=new Date().toISOString().slice(0,10);
  events.forEach(e=>{const s=stats[e.id]||{};views+=Number(s.views||0);clicks+=Number(s.link_clicks||0);today+=Number((s.days||[]).find(d=>d.day===todayKey)?.views||0)});
  totalViews.textContent=views.toLocaleString();totalClicks.textContent=clicks.toLocaleString();todayViews.textContent=today.toLocaleString();
  const create=document.querySelector(".hero .primary");
  if(planInfo.maxEvents!==null&&events.length>=planInfo.maxEvents){create.classList.add("plan-locked");create.textContent="🔒 Event limit reached";create.href="/plans/";}
  else{create.classList.remove("plan-locked");create.textContent="+ Create Event";create.href="index.html";}
  if(!events.length){root.innerHTML=`<div class="empty"><div class="empty-icon">◷</div><h2>No events yet</h2><p>Create your first countdown and share it with your audience.</p><a class="primary" href="index.html">Create your first event →</a></div>`;return}
  root.innerHTML=events.map(e=>{const url=`${location.origin}/event/${encodeURIComponent(e.event_slug)}`,statsUrl=`statistics.html?event=${encodeURIComponent(e.id)}`,paused=e.status!=="active",link=e.link_url||"",s=stats[e.id]||{};const statsAction=planInfo.statistics?`<a class="stats-action" href="${statsUrl}">Statistics</a>`:`<a class="stats-action locked-action" href="/plans/" title="Statistics are available on Pro and Premium">🔒 Statistics</a>`;return`<article class="event ${paused?"is-paused":""}"><div class="event-top"><div class="badges"><span class="badge ${paused?"paused":"active"}">${paused?"PAUSED":"ACTIVE"}</span><span class="badge">${esc(e.theme||"default")}</span></div><span class="event-id">#${esc(e.event_slug)}</span></div><h2>${esc(e.name)}</h2><p>${esc(e.description||"No description")}</p><div class="date"><span>EVENT DATE</span><strong>${esc(fmt(e.event_date))}</strong><small>${esc(e.timezone||"UTC")}</small></div><div class="event-stats"><div><strong>${Number(s.views||0).toLocaleString()}</strong><span>Views</span></div><div><strong>${Number(s.link_clicks||0).toLocaleString()}</strong><span>Link clicks</span></div><div><strong>${Number(s.days?.length||0)}</strong><span>Active days</span></div></div>${link?`<a class="event-link-preview" href="${esc(link)}" target="_blank" rel="noopener noreferrer">Event link ↗</a>`:`<div class="event-link-empty">No event link added</div>`}<div class="actions">${statsAction}<a href="${url}" target="_blank" rel="noopener">Preview</a><button data-copy="${esc(url)}">Copy Link</button><button data-embed="${esc(url)}" data-name="${esc(e.name)}">Embed</button><button data-edit="${esc(e.id)}">Edit</button><button class="toggle" data-toggle="${esc(e.id)}">${paused?"Activate":"Pause"}</button><button class="delete" data-delete="${esc(e.id)}">Delete</button></div></article>`}).join("");
}
async function api(url,options={}){const r=await fetch(url,{credentials:"same-origin",headers:{Accept:"application/json",...(options.body?{"Content-Type":"application/json"}:{})},...options}),d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(Error(d.error||"Request failed."),d);return d}
async function loadRules(){try{planInfo=await api("/api/tools/event-countdown/rules");renderPlan();applyThemeLocks()}catch(e){if(e?.status===401||e?.message==="Please sign in."){location.href="/login?next=/tools/utilities/event-countdown/dashboard.html";return}planPanel.innerHTML=`<div class="plan-error">Unable to load plan details.</div>`}}
async function loadStats(){stats=Object.fromEntries(await Promise.all(events.map(async e=>{try{return[e.id,await api(`/api/tools/event-countdown/events/${encodeURIComponent(e.id)}/stats`)]}catch(_){return[e.id,{views:0,link_clicks:0,days:[]}]}})))}
async function load(){try{await loadRules();const r=await fetch("/api/tools/event-countdown/events",{credentials:"same-origin",headers:{Accept:"application/json"}}),d=await r.json().catch(()=>({}));if(r.status===401){location.href="/login?next=/tools/utilities/event-countdown/dashboard.html";return}if(!r.ok)throw Object.assign(Error(d.error||"Unable to load events."),d);events=d.events||[];planInfo.eventsUsed=events.length;renderPlan();render();await loadStats();render()}catch(e){message.textContent=e.message;root.innerHTML=""}}
function openEdit(e){editingId=e.id;document.querySelector("#editName").value=e.name||"";document.querySelector("#editDescription").value=e.description||"";document.querySelector("#editDate").value=e.event_date||"";document.querySelector("#editTimezone").value=e.timezone||"UTC";document.querySelector("#editTheme").value=e.theme||"default";document.querySelector("#editImage").value=e.image_url||"";document.querySelector("#editLink").value=e.link_url||"";applyThemeLocks();if(!planInfo.allowedThemes.includes(e.theme))document.querySelector("#editTheme").value="default";editMessage.textContent="";modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.querySelector("#editName").focus()}
function closeEdit(){editingId=null;modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}
async function saveEdit(ev){ev.preventDefault();if(!editingId)return;const selected=editTheme.value;if(!planInfo.allowedThemes.includes(selected)){editMessage.innerHTML=`This theme is locked for your ${esc(planLabel())} plan. ${upgradeLink()}`;return}const b=form.querySelector(".save");b.disabled=true;b.textContent="Saving…";editMessage.textContent="";try{await api(`/api/tools/event-countdown/events/${encodeURIComponent(editingId)}`,{method:"PUT",body:JSON.stringify({name:document.querySelector("#editName").value.trim(),description:document.querySelector("#editDescription").value.trim(),event_date:document.querySelector("#editDate").value,timezone:document.querySelector("#editTimezone").value,theme:selected,image_url:document.querySelector("#editImage").value.trim(),link_url:document.querySelector("#editLink").value.trim()})});closeEdit();await load()}catch(e){editMessage.textContent=e.message;if(e.code==="THEME_NOT_AVAILABLE")editMessage.innerHTML=`This theme is locked for your ${esc(planLabel())} plan. ${upgradeLink()}`}finally{b.disabled=false;b.textContent="Save changes"}}
document.addEventListener("click",async ev=>{const locked=ev.target.closest(".locked-action");if(locked){ev.preventDefault();message.innerHTML=`Statistics are available on Pro and Premium. ${upgradeLink()}`;return}const copy=ev.target.closest("[data-copy]");if(copy){try{await navigator.clipboard.writeText(copy.dataset.copy);const old=copy.textContent;copy.textContent="Copied";setTimeout(()=>copy.textContent=old,1200)}catch(_){}return}const embed=ev.target.closest("[data-embed]");if(embed){const code=embedCode(embed.dataset.embed,embed.dataset.name);try{await navigator.clipboard.writeText(code);const old=embed.textContent;embed.textContent="Copied";setTimeout(()=>embed.textContent=old,1200)}catch(_){}return}const edit=ev.target.closest("[data-edit]");if(edit){const item=events.find(x=>x.id===edit.dataset.edit);if(item)openEdit(item);return}const toggle=ev.target.closest("[data-toggle]");if(toggle){const item=events.find(x=>x.id===toggle.dataset.toggle);if(!item)return;toggle.disabled=true;try{await api(`/api/tools/event-countdown/events/${encodeURIComponent(item.id)}`,{method:"PUT",body:JSON.stringify({name:item.name,description:item.description||"",event_date:item.event_date,timezone:item.timezone||"UTC",theme:item.theme||"default",image_url:item.image_url||"",link_url:item.link_url||"",status:item.status==="active"?"paused":"active"})});await load()}catch(e){message.textContent=e.message;toggle.disabled=false}return}const del=ev.target.closest("[data-delete]");if(del){if(!confirm("Delete this event? This cannot be undone."))return;del.disabled=true;try{await api(`/api/tools/event-countdown/events/${encodeURIComponent(del.dataset.delete)}`,{method:"DELETE"});events=events.filter(x=>x.id!==del.dataset.delete);delete stats[del.dataset.delete];planInfo.eventsUsed=events.length;renderPlan();render()}catch(e){message.textContent=e.message;del.disabled=false}}});
document.addEventListener("click",ev=>{if(ev.target.closest("[data-close]")||ev.target===modal)closeEdit()});document.addEventListener("keydown",ev=>{if(ev.key==="Escape"&&modal.classList.contains("open"))closeEdit()});form.addEventListener("submit",saveEdit);fillZones();load();