const {PDFDocument}=PDFLib;
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
const $=id=>document.getElementById(id);
const input=$('fileInput'),drop=$('dropZone'),choose=$('chooseBtn'),workspace=$('workspace'),grid=$('pageGrid'),meta=$('fileMeta');
const selectedCount=$('selectedCount'),hint=$('selectionHint'),rangeInput=$('pageRange');
const status=$('status'),statusTitle=$('statusTitle'),statusText=$('statusText'),errorBox=$('errorBox'),errorText=$('errorText'),result=$('result'),resultText=$('resultText');
const deleteBtn=$('deleteBtn'),downloadBtn=$('downloadBtn'),resetBtn=$('resetBtn'),clearBtn=$('clearBtn');
let sourceBytes=null,pages=[],outputBlob=null;
function messagesOff(){status.hidden=true;errorBox.hidden=true;result.hidden=true}
function progress(title,text){errorBox.hidden=true;result.hidden=true;statusTitle.textContent=title;statusText.textContent=text;status.hidden=false}
function error(message){status.hidden=true;result.hidden=true;errorText.textContent=message;errorBox.hidden=false}
function reset(){sourceBytes=null;pages=[];outputBlob=null;input.value='';grid.innerHTML='';meta.textContent='';rangeInput.value='';workspace.hidden=true;deleteBtn.disabled=true;messagesOff()}
function update(){const n=pages.filter(p=>p.remove).length;selectedCount.textContent=`${n} page${n===1?'':'s'} marked`;hint.textContent=n?'These pages will be removed.':'Click pages you want to delete.';deleteBtn.disabled=!sourceBytes||n===0||n>=pages.length}
function toggle(i,v){const p=pages[i];if(!p)return;p.remove=v;p.card.classList.toggle('selected',v);p.check.textContent=v?'✓':'';update()}
function parseRanges(value,total){const set=new Set();if(!value.trim())throw Error('Enter at least one page number or range.');for(const raw of value.split(',')){const s=raw.trim();if(/^\d+$/.test(s)){const n=+s;if(n<1||n>total)throw Error(`Page ${n} is outside the PDF.`);set.add(n-1);continue}const m=s.match(/^(\d+)\s*-\s*(\d+)$/);if(!m)throw Error(`Invalid page range: ${s}`);let a=+m[1],b=+m[2];if(a>b)[a,b]=[b,a];if(a<1||b>total)throw Error(`Range ${s} is outside the PDF.`);for(let n=a;n<=b;n++)set.add(n-1)}return set}
async function readBytes(file){const bytes=new Uint8Array(await file.arrayBuffer());if(bytes.length<5)throw Error('The selected file is too small to be a valid PDF.');if(new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')throw Error('This file does not contain a valid PDF header. Please choose a real PDF file.');return bytes}
async function loadPdf(file){if(!file||!(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf'))){error('Please choose a valid PDF file.');return}reset();progress('Reading your PDF…','Loading pages for preview');try{sourceBytes=await readBytes(file);const pdf=await pdfjsLib.getDocument({data:sourceBytes.slice()}).promise;if(!pdf.numPages)throw Error('The PDF contains no pages.');meta.textContent=`${pdf.numPages} page${pdf.numPages===1?'':'s'} · ${(file.size/1048576).toFixed(2)} MB`;workspace.hidden=false;for(let n=1;n<=pdf.numPages;n++){statusText.textContent=`Rendering page ${n} of ${pdf.numPages}`;const p=await pdf.getPage(n),base=p.getViewport({scale:1}),scale=Math.min(1.2,260/Math.max(base.width,base.height)),vp=p.getViewport({scale});const canvas=document.createElement('canvas');canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);await p.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;const card=document.createElement('article');card.className='page-card';const preview=document.createElement('div');preview.className='preview';preview.append(canvas);const check=document.createElement('div');check.className='check';preview.append(check);const info=document.createElement('div');info.className='page-info';const label=document.createElement('div');label.className='page-number';label.textContent=`Page ${n}`;info.append(label);card.append(preview,info);grid.append(card);const state={index:n-1,remove:false,card,check};pages.push(state);card.onclick=()=>toggle(n-1,!state.remove)}update();status.hidden=true}catch(e){workspace.hidden=true;sourceBytes=null;error(e?.message||'The PDF could not be read. Try another PDF file.')}}
function applyRanges(){try{if(!pages.length)throw Error('Choose a PDF before applying a page range.');const set=parseRanges(rangeInput.value,pages.length);pages.forEach((p,i)=>toggle(i,set.has(i)))}catch(e){error(e.message)}}
function selectAll(){if(!pages.length)return;pages.forEach((p,i)=>toggle(i,true));rangeInput.value=`1-${pages.length-1}`}
function clearSelection(){pages.forEach((p,i)=>toggle(i,false));rangeInput.value=''}
async function createPdf(){const removed=new Set(pages.filter(p=>p.remove).map(p=>p.index));if(!sourceBytes){error('Choose a PDF before deleting pages.');return}if(!removed.size){error('Select at least one page to remove.');return}if(removed.size>=pages.length){error('You must keep at least one page in the PDF.');return}deleteBtn.disabled=true;messagesOff();progress('Creating your PDF…','Removing selected pages');try{const source=await PDFDocument.load(sourceBytes.slice(),{ignoreEncryption:false});const output=await PDFDocument.create();const keep=pages.filter(p=>!p.remove).map(p=>p.index);const copied=await output.copyPages(source,keep);copied.forEach(p=>output.addPage(p));const bytes=await output.save({useObjectStreams:true});if(!bytes.length)throw Error('The PDF could not be generated.');outputBlob=new Blob([bytes],{type:'application/pdf'});status.hidden=true;resultText.textContent=`${keep.length} page${keep.length===1?'':'s'} kept · ${removed.size} removed · ${(outputBlob.size/1048576).toFixed(2)} MB`;result.hidden=false}catch(e){error(e?.message||'The pages could not be deleted. The PDF may be damaged, encrypted or protected.')}finally{update()}}
function download(){if(!outputBlob)return;const url=URL.createObjectURL(outputBlob),a=document.createElement('a');a.href=url;a.download='nexauren-pdf-without-pages.pdf';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
choose.onclick=e=>{e.stopPropagation();input.click()};drop.onclick=e=>{if(!e.target.closest('button'))input.click()};drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}};input.onchange=()=>{const f=input.files?.[0];if(f)loadPdf(f);input.value=''};drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragover')};drop.ondragleave=()=>drop.classList.remove('dragover');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragover');loadPdf(e.dataTransfer.files?.[0])};$('applyRange').onclick=applyRanges;rangeInput.onkeydown=e=>{if(e.key==='Enter')applyRanges()};$('selectAll').onclick=selectAll;$('clearSelection').onclick=clearSelection;clearBtn.onclick=reset;resetBtn.onclick=reset;downloadBtn.onclick=download;deleteBtn.onclick=createPdf;messagesOff();
