const $=id=>document.getElementById(id);
const state={title:"",description:"",features:[],tags:[],faq:[]};
function clean(value){return value.trim().replace(/\s+/g," ")}
function titleCase(value){return value.replace(/\b\w/g,char=>char.toUpperCase())}
function makeTitle(name,category,tone){const prefix=tone==="Premium"?"Premium ":tone==="Friendly"?"Smart ":"";return `${prefix}${clean(name)}${category?` — ${clean(category)}`:""}`.slice(0,120)}
function makeDescription(name,details,audience,tone){const opening=tone==="Friendly"?`Meet ${name}, a practical choice for ${audience.toLowerCase()}.`:tone==="Premium"?`${name} is designed for customers who value a polished, dependable experience.`:`${name} is a practical solution for ${audience.toLowerCase()} looking for useful features and straightforward value.`;const extra=details?` ${details}`:" Designed with a clear focus on usability and everyday performance.";return opening+extra}
function makeTags(name,category,features){const words=(name+" "+category+" "+features.join(" ")).toLowerCase().match(/[a-z0-9À-ÿ]+/gi)||[];const stop=new Set(["the","and","for","with","from","this","that","your","one","per","com","uma","para","com","que","dos","das"]);const unique=[];for(const word of words){if(word.length<4||stop.has(word)||unique.includes(word))continue;unique.push(word);if(unique.length===10)break}return unique}
function render(){ $("outTitle").textContent=state.title;$("outDescription").textContent=state.description;$("outFeatures").innerHTML=state.features.map(item=>`<li>${escapeHtml(item)}</li>`).join("");$("outTags").innerHTML=state.tags.map(tag=>`<span class="tag">${escapeHtml(tag)}</span>`).join("");$("outFaq").innerHTML=state.faq.map(item=>`<div class="faq"><strong>${escapeHtml(item.q)}</strong><span>${escapeHtml(item.a)}</span></div>`).join("");$("empty").hidden=true;$("result").hidden=false;$("copy").disabled=false}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[char]))}
function generate(){const name=clean($("name").value);if(!name){$("status").textContent="Add a product name to continue.";$("name").focus();return}const category=clean($("category").value);const features=$("features").value.split(/\n|,/).map(clean).filter(Boolean).slice(0,8);const details=clean($("details").value);const audience=$("audience").value;const tone=$("tone").value;state.title=makeTitle(name,category,tone);state.description=makeDescription(name,details,audience,tone);state.features=features.length?features:["Designed for straightforward everyday use","Clear product presentation","Practical value for the intended customer"];state.tags=makeTags(name,category,features);state.faq=[{q:"What is this product?",a:`${name} is a ${category||"practical product"} designed for ${audience.toLowerCase()}.`},{q:"Who is it for?",a:`It is suitable for ${audience.toLowerCase()} looking for a clear, useful solution.`},{q:"What should I check before publishing?",a:"Confirm specifications, compatibility, availability, pricing and any claims against the actual product."}];render();$("status").textContent="Listing generated locally."}
$("generate").addEventListener("click",generate);
$("copy").addEventListener("click",async()=>{const text=[state.title,"",state.description,"","KEY FEATURES",...state.features.map(x=>`• ${x}`),"","TAGS",state.tags.join(", "),"","FAQ",...state.faq.flatMap(x=>[x.q,x.a])].join("\n");try{await navigator.clipboard.writeText(text);$("status").textContent="Listing copied to clipboard."}catch{$("status").textContent="Copy is unavailable in this browser."}});
$("features").addEventListener("keydown",event=>{if(event.key==="Enter"&&!event.shiftKey){event.stopPropagation()}});
