const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const num=v=>Number(v||0).toLocaleString();
const duration=ms=>{const s=Math.round(Number(ms||0)/1000);if(!s)return"0s";if(s<60)return`${s}s`;const m=Math.floor(s/60),r=s%60;return r?`${m}m ${r}s`:`${m}m`;};
function notice(msg,error=false){const n=$("notice");n.textContent=msg;n.className=error?"notice error":"notice";n.hidden=false;clearTimeout(notice.t);notice.t=setTimeout(()=>n.hidden=true,4000);}
async function api(url){const r=await fetch(url,{credentials:"same-origin",cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.status===401){location.replace("/login/");throw Error("Sign in required.");}if(!r.ok)throw Error(d.error||"Could not load analytics.");return d;}
function rows(items,labelKey,valueKey,formatter=x=>num(x),empty="No data yet."){if(!items?.length)return`<div class="item"><div class="item-meta">${empty}</div></div>`;return items.map(x=>`<div class="item"><div class="item-main"><div class="item-title">${esc(x[labelKey]||"Unknown")}</div></div><div class="item-value">${formatter(x[valueKey])}</div></div>`).join("");}
function renderChart(data){const box=$("chart");if(!data.length){box.innerHTML='<div class="item-meta">No analytics data for this period.</div>';return;}const max=Math.max(1,...data.flatMap(x=>[Number(x.views||0),Number(x.clicks||0),Number(x.reads||0)]));box.innerHTML=data.map(x=>{const v=Number(x.views||0),c=Number(x.clicks||0),r=Number(x.reads||0);return`<div style="flex:1;min-width:18px;height:100%;display:flex;flex-direction:column;justify-content:flex-end"><div class="bar-day" title="${esc(x.day)} · ${v} views"><i class="bar views" style="height:${Math.max(v?3:0,v/max*92)}%"></i><i class="bar clicks" style="height:${Math.max(c?3:0,c/max*92)}%"></i><i class="bar reads" style="height:${Math.max(r?3:0,r/max*92)}%"></i></div><div class="day-label">${esc(x.day.slice(5))}</div></div>`;}).join("")+`<div class="legend"><span><i style="background:#3157e8"></i>Views</span><span><i style="background:#7657e8"></i>Clicks</span><span><i style="background:#1aa56d"></i>Reads</span></div>`;}
function render(data){$("views").textContent=num(data.summary.views);$("clicks").textContent=num(data.summary.clicks);$("reads").textContent=num(data.summary.engaged_reads);$("time").textContent=duration(data.summary.avg_read_ms);$("period").textContent=`${data.range.from} → ${data.range.to}`;renderChart(data.daily);$("posts").innerHTML=data.top_posts.map(p=>`<div class="item"><div class="item-main"><div class="item-title">${esc(p.title)}</div><div class="item-meta">${num(p.views)} views · ${num(p.clicks)} clicks · ${duration(p.avg_read_ms)} avg read</div></div><div class="item-value">${num(p.views)}</div></div>`).join("")||'<div class="item-meta">No posts viewed yet.</div>';$('sources').innerHTML=rows(data.sources,"source","visits");$('countries').innerHTML=rows(data.countries,"country","visits");$('devices').innerHTML=rows(data.devices,"device","visits");$('browsers').innerHTML=rows(data.browsers,"browser","visits");}
async function load(){try{let range=$("range").value;let url="/api/blog/admin/analytics?";if(range==="custom")url+=`from=${encodeURIComponent($("from").value)}&to=${encodeURIComponent($("to").value)}`;else url+=`range=${range}`;const data=await api(url);render(data);}catch(e){notice(e.message,true);}}
$("range").addEventListener("change",()=>{$("custom").hidden=$("range").value!=="custom";if($("range").value!=="custom")load();});$("apply").addEventListener("click",()=>{if(!$("from").value||!$("to").value)return notice("Choose both dates.",true);load();});
const today=new Date(),ago=new Date(today);ago.setDate(today.getDate()-6);$("from").value=ago.toISOString().slice(0,10);$("to").value=today.toISOString().slice(0,10);load();
