const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const num=v=>Number(v||0).toLocaleString();
const duration=ms=>{const s=Math.round(Number(ms||0)/1000);if(!s)return"0s";if(s<60)return`${s}s`;const m=Math.floor(s/60),r=s%60;return r?`${m}m ${r}s`:`${m}m`;};
function notice(msg,error=false){const n=$("notice");if(!n)return;n.textContent=msg;n.className=error?"notice error":"notice";n.hidden=false;clearTimeout(notice.t);notice.t=setTimeout(()=>n.hidden=true,4500);}
async function api(url){const r=await fetch(url,{credentials:"same-origin",cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.status===401){location.replace("/login/");throw Error("Sign in required.");}if(!r.ok)throw Error(d.error||"Could not load analytics.");return d;}
function pct(now,old){if(!old)return null;return Math.round((now-old)/old*100);}
function setChange(id,value){const el=$(id);if(value===null){el.textContent="No previous data";el.className="change";return;}el.textContent=`${value>=0?"↑":"↓"} ${Math.abs(value)}% vs previous period`;el.className=`change ${value>0?"up":value<0?"down":"neutral"}`;}
function rows(items,labelKey,valueKey){if(!items?.length)return'<div class="item"><div class="item-meta">No data yet.</div></div>';const max=Math.max(1,...items.map(x=>Number(x[valueKey]||0)));return items.map(x=>{const v=Number(x[valueKey]||0),w=Math.round(v/max*100);return`<div class="item"><div class="item-main"><div class="item-title">${esc(x[labelKey]||"Unknown")}</div><div class="mini-bar"><i style="width:${w}%"></i></div></div><div class="item-value">${num(v)}</div></div>`}).join("");}
function renderChart(data){const box=$("chart");if(!data?.length){box.innerHTML='<div class="item-meta">No analytics data for this period.</div>';return;}const width=900,height=235,pad=24,max=Math.max(1,...data.flatMap(x=>[Number(x.views||0),Number(x.clicks||0),Number(x.reads||0)]));const points=key=>data.map((x,i)=>{const px=pad+(data.length===1?(width-pad*2)/2:i*(width-pad*2)/(data.length-1));const value=Number(x[key]||0);const py=height-pad-(value/max)*(height-pad*2);return`${px},${py}`}).join(" ");const labels=data.map((x,i)=>{if(i%Math.max(1,Math.ceil(data.length/7))!==0&&i!==data.length-1)return"";const px=pad+(data.length===1?(width-pad*2)/2:i*(width-pad*2)/(data.length-1));return`<text x="${px}" y="${height-4}" text-anchor="middle">${esc(String(x.day).slice(5))}</text>`}).join("");box.innerHTML=`<svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="none"><line class="grid" x1="${pad}" y1="${height-pad}" x2="${width-pad}" y2="${height-pad}"/><line class="grid" x1="${pad}" y1="${height/2}" x2="${width-pad}" y2="${height/2}"/><line class="grid" x1="${pad}" y1="${pad}" x2="${width-pad}" y2="${pad}"/><polyline class="line views-line" points="${points("views")}"/><polyline class="line reads-line" points="${points("reads")}"/><polyline class="line clicks-line" points="${points("clicks")}"/>${labels}</svg><div class="legend"><span><i class="lv"></i>Views</span><span><i class="lr"></i>Reads</span><span><i class="lc"></i>Clicks</span></div>`;}
function render(data,old){const s=data.summary||{};$("views").textContent=num(s.views);$("clicks").textContent=num(s.clicks);$("reads").textContent=num(s.engaged_reads);$("time").textContent=duration(s.avg_read_ms);$("unique").textContent="—";setChange("viewsChange",pct(s.views,old?.summary?.views));setChange("clicksChange",pct(s.clicks,old?.summary?.clicks));setChange("readsChange",pct(s.engaged_reads,old?.summary?.engaged_reads));setChange("timeChange",pct(s.avg_read_ms,old?.summary?.avg_read_ms));setChange("uniqueChange",null);$("period").textContent=`${data.range.from} → ${data.range.to}`;renderChart(data.daily);$("posts").innerHTML=(data.top_posts||[]).map(p=>`<div class="item"><div class="item-main"><div class="item-title">${esc(p.title)}</div><div class="item-meta">${num(p.views)} views · ${num(p.clicks)} clicks · ${duration(p.avg_read_ms)} avg read</div></div><div class="item-value">${num(p.views)}</div></div>`).join("")||'<div class="item-meta">No posts viewed yet.</div>';$('sources').innerHTML=rows(data.sources,"source","visits");$('countries').innerHTML=rows(data.countries,"country","visits");$('devices').innerHTML=rows(data.devices,"device","visits");$('browsers').innerHTML=rows(data.browsers,"browser","visits");}
function datesForRange(range){const today=new Date();const end=new Date(today);end.setHours(0,0,0,0);let start=new Date(end);if(range==="today"){}else if(range==="90")start.setDate(start.getDate()-89);else start.setDate(start.getDate()-(Number(range)-1));return{from:start.toISOString().slice(0,10),to:end.toISOString().slice(0,10)};}
function previousDates(from,to){const a=new Date(`${from}T00:00:00`),b=new Date(`${to}T00:00:00`);const days=Math.max(1,Math.round((b-a)/86400000)+1);const end=new Date(a);end.setDate(end.getDate()-1);const start=new Date(end);start.setDate(start.getDate()-days+1);return{from:start.toISOString().slice(0,10),to:end.toISOString().slice(0,10)};}
async function load(){try{$("app")?.classList.add("loading");let range=$("range").value;let dates=range==="custom"?{from:$("from").value,to:$("to").value}:datesForRange(range);if(!dates.from||!dates.to)throw Error("Choose both dates.");const slug=$("post")?.value||"";let q=`from=${encodeURIComponent(dates.from)}&to=${encodeURIComponent(dates.to)}`;if(slug)q+=`&slug=${encodeURIComponent(slug)}`;const prev=previousDates(dates.from,dates.to);let pq=`from=${encodeURIComponent(prev.from)}&to=${encodeURIComponent(prev.to)}`;if(slug)pq+=`&slug=${encodeURIComponent(slug)}`;const [data,old]=await Promise.all([api(`/api/blog/admin/analytics?${q}`),api(`/api/blog/admin/analytics?${pq}`).catch(()=>null)]);render(data,old);$("from").value=dates.from;$("to").value=dates.to;}catch(e){notice(e.message,true);}finally{$("app")?.classList.remove("loading");}}
$("range").addEventListener("change",()=>{$("custom").hidden=$("range").value!=="custom";if($("range").value!=="custom")load();});$("apply").addEventListener("click",()=>{if(!$("from").value||!$("to").value)return notice("Choose both dates.",true);load();});
const today=new Date(),ago=new Date(today);ago.setDate(today.getDate()-6);$("from").value=ago.toISOString().slice(0,10);$("to").value=today.toISOString().slice(0,10);load();